version: "3"

services:
  vietlott:
    image: duclm2609/vietlott:latest
    container_name: vietlott
    env_file:
      - .env
    restart: always
    ports:
      - 8181:8181

networks:
  default:
    external:
      name: docker-network